export const routeConstants = {
    ADD_POINT: 'ROUTE_ADD_POINT',
    DELETE_POINT: 'ROUTE_DELETE_POINT',
    REPLACE_POINT: 'ROUTE_REPLACE_POINT',
    REORDER_POINTS: 'ROUTE_REORDER_POINTS',
    SET_ROUTE: 'ROUTE_SET_ROUTE'
};